<img style="float: left; margin: 30px 15px 15px 15px;" src="https://oci02.img.iteso.mx/Identidades-De-Instancia/ITESO/Logos%20ITESO/Logo-ITESO-Principal.jpg" width="400" height="600" /> 
    
    
## <font color='navy'> Teoría Pos-Moderna de Portafolios: Práctica
    
### <font color='navy'> Portafolios de Inversión

    Mtro. Sean Nicolás González Vázquez

---

### <font color='navy'> 0.- Introducción
    
En la sesión anterior, exploramos varios métodos de la **Teoría Posmoderna de Portafolios (TPMP)**, que se enfoca en la optimización de portafolios separando claramente el riesgo en dos componentes: el downside y el upside risk. 
    
A grandes rasgos, esta teoría amplía la clásica Teoría Moderna de Portafolios, al poner énfasis en los riesgos que afectan negativamente las inversiones, y aquellos que representan oportunidades de ganancia.

La principal contribución de este enfoque radica en su capacidad para descomponer el riesgo en dos categorías clave:

+ **Downside risk**: Riesgo de incurrir en pérdidas, es decir, cuando los rendimientos caen por debajo de un umbral establecido, como podría ser un benchmark o simplemente rendimientos negativos.   
    
    
+ **Upside risk**: Riesgo (potencial) de obtener ganancias.   
    
    
+ Mientras que el downside implica posibles pérdidas para el portafolio, el upside representa las oportunidades de obtener rendimientos positivos.

Dentro de esta estructura, profundizamos en **dos métodos de Asset Allocation** basados en esta separación de riesgos: el método de la **Mínima Semivarianza** y el método de **Máximo Omega**. 
    
Ambos enfoques proporcionan alternativas interesantes a los modelos tradicionales propuestos por Markowitz y Sharpe.   
    
El primero, la Mínima Semivarianza, es una extensión del clásico método de Mínima Varianza, ya que se centra exclusivamente en minimizar el riesgo a la baja (downside risk), ignorando las fluctuaciones al alza. El segundo, el Máximo Omega, es una alternativa al Ratio de Sharpe, con la diferencia clave de que se enfoca en maximizar la relación entre las ganancias potenciales (upside) y las pérdidas posibles (downside), proporcionando una evaluación más matizada del rendimiento ajustado al riesgo.

> Con este contexto, implementaremos ambos métodos, utilizando optimización montecarlo.

---

### <font color='navy'> 1.- Descarga de Datos y Obtención de Métricas

En este ejercicio, vamos a construir un portafolio compuesto por siete activos financieros previamente seleccionados:

+ PG: Procter & Gamble
+ COST: Costco Wholesale
+ KO: Coca-Cola
+ WMT: Walmart
+ CLX: Clorox
+ K: Kellogg's
+ KHC: Kraft Heinz

Como puedes observar, todos estos activos pertenecen a compañías que producen bienes de consumo básico, tales como productos de limpieza, alimentos y bebidas, entre otros. 


Estos activos forman parte de un sector específico conocido como Consumer Staples. Este sector es considerado anticíclico por naturaleza. Por ello, se le clasifica como un sector defensivo, ideal para inversiónistas que buscan estabilidad y son aversos al riesgo.

> **Consumer Staples:** Hace referencia a bienes de consumo necesarios para la vida diaria, como alimentos, bebidas, productos de higiene personal y del hogar. Estos productos suelen ser demandados de forma constante, independientemente del ciclo económico.  

> **Sector Defensivo:** Se refiere a aquellos sectores de la economía cuyos activos tienden a ser menos volátiles y más resilientes en tiempos de crisis o desaceleraciones económicas. Las empresas en estos sectores producen bienes y servicios esenciales, lo que les permite mantener una demanda relativamente estable incluso en condiciones adversas del mercado.


Como gestor del portafolio (portfolio manager), tu objetivo es encontrar las ponderaciones óptimas que minimicen la semivarianza del portafolio y maximicen el ratio de Omega.

In [50]:
# Importación de Librerías
import numpy as np
import pandas as pd
import yfinance as yf

np.set_printoptions(suppress=True, precision=6)

In [2]:
# Descarga de Datos
prices=yf.download(['PG', 'COST', 'KO', 'WMT', 'CLX', 'KHC'], 
                    start='2020-01-01', end='2026-03-06')['Close']

/home/rigodev/ITESO/06/portafolios/env/lib/python3.12/site-packages/yfinance/scrapers/history.py:201: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
[*********************100%***********************]  6 of 6 completed

In [3]:
prices.head()

Ticker,CLX,COST,KHC,KO,PG,WMT
Date,,,,,,
2020-01-02,126.064590,266.497467,23.362871,45.745106,105.524033,36.433834
2020-01-03,126.312401,266.716980,23.089411,45.495541,104.814331,36.112194
2020-01-06,126.692390,266.790100,23.141142,45.478901,104.959663,36.038677
2020-01-07,125.164185,266.369598,22.734640,45.129520,104.309830,35.704792
2020-01-08,125.535912,269.423248,22.608990,45.212700,104.754456,35.582256

In [4]:
# Calculo de rendimientos
returns = prices.pct_change().dropna()

In [5]:
# Calcular rendimiento promedio
assets_mean_return = returns.mean()
assets_mean_return

Ticker
CLX     0.000073
COST    0.000954
KHC     0.000155
KO      0.000418
PG      0.000328
WMT     0.000893
dtype: float64

In [6]:
# Calcular matriz de correlación
assets_corr = returns.corr()
assets_corr

Ticker       CLX      COST       KHC        KO        PG       WMT
Ticker
CLX     1.000000  0.326487  0.376578  0.334535  0.506711  0.312927
COST    0.326487  1.000000  0.307689  0.424536  0.483058  0.611316
KHC     0.376578  0.307689  1.000000  0.551005  0.535309  0.319343
KO      0.334535  0.424536  0.551005  1.000000  0.646583  0.370351
PG      0.506711  0.483058  0.535309  0.646583  1.000000  0.476900
WMT     0.312927  0.611316  0.319343  0.370351  0.476900  1.000000

---

### <font color='navy'> 2.- Portafolio Eficiente en Mínima Semivarianza  
    
  
### <font color='navy'>  **Mínima Semivarianza**

Método de la optimización de portafolios que busca minimizar el potencial riesgo de pérdida (*downside risk*) de un portafolio de inversión. ´


**Separar los rendimientos por debajo de 0 (pérdidas), las ganancias convertirlas en cero.**

$$R_{below, i} = min(r_i, 0)$$

In [7]:
below_zero = returns[returns < 0].fillna(0)
below_zero.head()

Ticker           CLX      COST       KHC        KO        PG       WMT
Date
2020-01-03  0.000000  0.000000 -0.011705 -0.005456 -0.006725 -0.008828
2020-01-06  0.000000  0.000000  0.000000 -0.000366  0.000000 -0.002036
2020-01-07 -0.012062 -0.001576 -0.017566 -0.007682 -0.006191 -0.009265
2020-01-08  0.000000  0.000000 -0.005527  0.000000  0.000000 -0.003432
2020-01-09  0.000000  0.000000 -0.000327  0.000000  0.000000  0.000000

**Calcular downside risk para cada activo.**

$$\sigma_{d, i} = \sigma(R_{below, i})$$

In [8]:
# Calcular downside risk
downside_risk = np.array(below_zero.std())
downside_risk

array([0.01062705, 0.00905878, 0.01060862, 0.0081278 , 0.00817945,
       0.00873361])

**Calcular matriz de Semivarianza.**

Antes de encontrar la matriz de semivarianza, simplifiquemos el cálculo......

Recordando, la varianza de dos activos financieros si tenemos la correlación entre ambos y sus desviaciones estandár individuales esta dada por $\sigma^2_{i, j} = \rho_{i, j} \sigma_i \sigma_j$. Para calcular la semi-varianza entre dos activos financieros utilizamos la misma fórmula, simplemente cambiando la desviación estandár por la semi-desviación (el *downside risk*), es decir, la semivarianza para dos activos financieros esta dada por $\sigma^2_{d(i, j)} = \rho_{i, j} \sigma_{(d, i)} \sigma_{(d, j)}$.

Esto debe hacerse iterativamente hasta construir la matriz de semivarianza, como vimos en la clase pasada. 

Para simplificar el ejercicio, podemos tomar el vector de $nx1$ de los downside risk individuales:

$$\sigma_d = \begin{bmatrix}
\sigma_{d, 1} \\
\sigma_{d, 2} \\
\vdots \\
\sigma_{d, n}
\end{bmatrix}$$

Y multiplicarla matricialmente por su transpuesta:

$$\sigma_d \sigma_d^T = 
\begin{bmatrix}
\sigma_{d, 1} \\
\sigma_{d, 2} \\
\vdots \\
\sigma_{d, n}
\end{bmatrix}
\begin{bmatrix}
\sigma_{d, 1} & \sigma_{d, 2} & \cdots & \sigma_{d, n}
\end{bmatrix}
=
\begin{bmatrix}
\sigma_{d, 1}^2 & \sigma_{d, 1} \sigma_{d, 2} & \cdots & \sigma_{d, 1} \sigma_{d, n} \\
\sigma_{d, 2} \sigma_{d, 1} & \sigma_{d, 2}^2 & \cdots & \sigma_{d, 2} \sigma_{d, n} \\
\vdots & \vdots & \ddots & \vdots \\
\sigma_{d, n} \sigma_{d, 1} & \sigma_{d, n} \sigma_{d, 2} & \cdots & \sigma_{d, n}^2
\end{bmatrix}$$

Notesé que esto equivale a multiplicar el elemento $i$ con el $j$ de la matriz de semivarianza, donde la diagonal son los downside al cuadrado (puedes utilizar la función de `np.multiply`). Finalmente realizamos el producto Hadamard de esta matriz con la matriz de correlación y con esto obtenemos la matriz de semivarianza.

$$S = \begin{bmatrix}
1 & \rho_{12} & \cdots & \rho_{1n} \\
\rho_{21} & 1 & \cdots & \rho_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
\rho_{n1} & \rho_{n2} & \cdots & 1
\end{bmatrix} \circ \begin{bmatrix}
\sigma_{d, 1}^2 & \sigma_{d, 1} \sigma_{d, 2} & \cdots & \sigma_{d, 1} \sigma_{d, n} \\
\sigma_{d, 2} \sigma_{d, 1} & \sigma_{d, 2}^2 & \cdots & \sigma_{d, 2} \sigma_{d, n} \\
\vdots & \vdots & \ddots & \vdots \\
\sigma_{d, n} \sigma_{d, 1} & \sigma_{d, n} \sigma_{d, 2} & \cdots & \sigma_{d, n}^2
\end{bmatrix}$$

El producto [Hadamard](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)#:~:text=In%20mathematics,%20the%20Hadamard%20product%20also%20known%20as%20the) es una multiplicación elemento a elemento de cada matriz según su posición específica (para realizarla en python, puedes utilizar simplimente `*`). Al realizar esta operación obtenemos la matriz de semivarianza para el portafolio:

$$S=
\begin{bmatrix}
\sigma_{d, 1}^2 & \rho_{12} \sigma_{d, 1} \sigma_{d, 2} & \cdots & \rho_{1n} \sigma_{d, 1} \sigma_{d, n} \\
\rho_{21} \sigma_{d, 2} \sigma_{d, 1} & \sigma_{d, 2}^2 & \cdots & \rho_{2n} \sigma_{d, 2} \sigma_{d, n} \\
\vdots & \vdots & \ddots & \vdots \\
\rho_{n1} \sigma_{d, n} \sigma_{d, 1} & \rho_{n2} \sigma_{d, n} \sigma_{d, 2} & \cdots & \sigma_{d, n}^2
\end{bmatrix}$$

**Calcular la matriz de semivarianza del portafolio.**

Con la matriz de semivarianza, podemos obtener la semivarianza de un portafolio de inversión con la fórmula:

$$s = w^T S w$$

In [9]:
semivar_matrix = downside_risk.reshape(len(returns.columns), 1) @ downside_risk.reshape(1, len(returns.columns)) * assets_corr
semivar_matrix

Ticker       CLX      COST       KHC        KO        PG       WMT
Ticker
CLX     0.000113  0.000031  0.000042  0.000029  0.000044  0.000029
COST    0.000031  0.000082  0.000030  0.000031  0.000036  0.000048
KHC     0.000042  0.000030  0.000113  0.000048  0.000046  0.000030
KO      0.000029  0.000031  0.000048  0.000066  0.000043  0.000026
PG      0.000044  0.000036  0.000046  0.000043  0.000067  0.000034
WMT     0.000029  0.000048  0.000030  0.000026  0.000034  0.000076

**Minimizar semivarianza cambiando ponderaciones.**

$$min_w \hspace{0.5cm} \sigma_d^2 = w^T S w$$
    
$$s.a. \hspace{0.5cm} \sum_{i=1}^n w_i = 1$$
 
$$\hspace{0.8cm} w_i > 0 $$

In [10]:
# Simular portafolios con montecarlo
np.random.seed(21)
n_sims = 100_000

w_aleatorio = np.random.dirichlet(np.ones(len(returns.columns)), size=n_sims)

semivar = [w.T @ semivar_matrix @ w for w in w_aleatorio]
semivar

[np.float64(7.0326289705161e-05),
 np.float64(4.696563578931553e-05),
 np.float64(4.5945085907822944e-05),
 np.float64(4.484495969185724e-05),
 np.float64(5.572891789033419e-05),
 np.float64(4.6232618075931257e-05),
 np.float64(5.1021966512003174e-05),
 np.float64(4.751448704887696e-05),
 np.float64(4.678960746260843e-05),
 np.float64(4.7894210737793744e-05),
 np.float64(4.802328882241924e-05),
 np.float64(5.3822070185484487e-05),
 np.float64(5.053880224794858e-05),
 np.float64(6.061645304604062e-05),
 np.float64(4.8596572627384997e-05),
 np.float64(4.7826033414827504e-05),
 np.float64(4.773119980118494e-05),
 np.float64(4.861467555126936e-05),
 np.float64(5.846724170849038e-05),
 np.float64(4.99815139886819e-05),
 np.float64(4.641975710837236e-05),
 np.float64(5.070598605561316e-05),
 np.float64(5.311663277365508e-05),
 np.float64(4.816256893735101e-05),
 np.float64(5.512531151618529e-05),
 np.float64(4.599906505726498e-05),
 np.float64(5.285739141729875e-05),
 np.float64(4.648971780218289e-05),
 np.float64(5.970774306583789e-05),
 np.float64(5.011734472295041e-05),
 np.float64(4.5396318971777163e-05),
 np.float64(5.25695885830084e-05),
 np.float64(4.643826698320606e-05),
 np.float64(4.541128226659647e-05),
 np.float64(6.592552671367078e-05),
 np.float64(5.0543318916595566e-05),
 np.float64(4.9668621600611905e-05),
 np.float64(4.843306243601586e-05),
 np.float64(5.4612271013803425e-05),
 np.float64(6.417470306145655e-05),
 np.float64(4.9349299232443584e-05),
 np.float64(5.156618878526053e-05),
 np.float64(4.9407507414872506e-05),
 np.float64(5.297973144300223e-05),
 np.float64(4.813589921817061e-05),
 np.float64(5.243216927975718e-05),
 np.float64(4.444786750230279e-05),
 np.float64(4.6267831976679806e-05),
 np.float64(5.35806325259337e-05),
 np.float64(4.70906264904207e-05),
 np.float64(4.640678710959147e-05),
 np.float64(4.7069232201759244e-05),
 np.float64(5.576101977263981e-05),
 np.float64(4.548458455579221e-05),
 np.float64(4.790019409514479e-05),
 np.float64(4.919132913372383e-05),
 np.float64(5.988674875292327e-05),
 np.float64(5.516396164424457e-05),
 np.float64(4.547837799505548e-05),
 np.float64(4.707006280607752e-05),
 np.float64(4.8284530054358906e-05),
 np.float64(5.140480261635553e-05),
 np.float64(5.563945105459884e-05),
 np.float64(5.257605969664251e-05),
 np.float64(4.387062273385525e-05),
 np.float64(4.8128299222680376e-05),
 np.float64(5.294190090506637e-05),
 np.float64(5.0738416982784e-05),
 np.float64(5.113408093196034e-05),
 np.float64(4.852316467131823e-05),
 np.float64(4.958793524857507e-05),
 np.float64(5.14364671214917e-05),
 np.float64(4.601942049418706e-05),
 np.float64(4.983013739418574e-05),
 np.float64(4.8396378066768425e-05),
 np.float64(5.214527103494598e-05),
 np.float64(5.307625280189215e-05),
 np.float64(4.826750811659939e-05),
 np.float64(5.078055948686704e-05),
 np.float64(4.881731694209534e-05),
 np.float64(4.977303195096796e-05),
 np.float64(4.793794182555006e-05),
 np.float64(4.751030705244294e-05),
 np.float64(5.2592893641493115e-05),
 np.float64(4.931217698403032e-05),
 np.float64(5.923948490495636e-05),
 np.float64(4.809885356890082e-05),
 np.float64(4.4973371010025475e-05),
 np.float64(4.699471905963506e-05),
 np.float64(4.445637148292033e-05),
 np.float64(5.635511576868166e-05),
 np.float64(6.764712583719029e-05),
 np.float64(4.92321138317392e-05),
 np.float64(5.027401628132132e-05),
 np.float64(4.741055263641207e-05),
 np.float64(5.5184434191714936e-05),
 np.float64(4.892202507233104e-05),
 np.float64(5.100068481570805e-05),
 np.float64(4.925397722998435e-05),
 np.float64(5.3290626639408006e-05),
 np.float64(5.389542834634627e-05),
 np.float64(5.2926421935431975e-05),
 np.float64(5.303420924583017e-05),
 np.float64(5.327934994807244e-05),
 np.float64(4.6971903576600235e-05),
 np.float64(6.86450425997341e-05),
 np.float64(5.344472954509295e-05),
 np.float64(6.431415157448486e-05),
 np.float64(5.474875552568369e-05),
 np.float64(4.8030564058821256e-05),
 np.float64(5.608477375073675e-05),
 np.float64(4.876585774024471e-05),
 np.float64(5.079934898148635e-05),
 np.float64(4.723225936992872e-05),
 np.float64(5.419052625112024e-05),
 np.float64(4.8816037340693825e-05),
 np.float64(4.792923281753583e-05),
 np.float64(4.691485927227223e-05),
 np.float64(5.546758525122815e-05),
 np.float64(4.660166982279839e-05),
 np.float64(5.1279848759874085e-05),
 np.float64(4.6121525232814247e-05),
 np.float64(6.154470459955236e-05),
 np.float64(4.710487340470337e-05),
 np.float64(6.85509887869801e-05),
 np.float64(4.7295744127527006e-05),
 np.float64(6.296936070947753e-05),
 np.float64(4.849229010596078e-05),
 np.float64(4.9690270101163366e-05),
 np.float64(5.507852305069416e-05),
 np.float64(4.38853627360806e-05),
 np.float64(4.957011203632459e-05),
 np.float64(5.001468092385475e-05),
 np.float64(5.8712594950154e-05),
 np.float64(4.43959388946325e-05),
 np.float64(5.4463667060005205e-05),
 np.float64(4.332715070742164e-05),
 np.float64(4.7677317392124794e-05),
 np.float64(5.6507741500621314e-05),
 np.float64(6.0067960263708426e-05),
 np.float64(5.101833655587243e-05),
 np.float64(4.8178983839136744e-05),
 np.float64(5.408514123829734e-05),
 np.float64(4.576955514347208e-05),
 np.float64(5.249277721147108e-05),
 np.float64(4.909895390804112e-05),
 np.float64(4.852654603414751e-05),
 np.float64(6.0849756981807925e-05),
 np.float64(4.4571956311488105e-05),
 np.float64(4.565248072893712e-05),
 np.float64(4.6934207510393486e-05),
 np.float64(5.0063488805540665e-05),
 np.float64(5.247070156285022e-05),
 np.float64(4.509855875828507e-05),
 np.float64(4.965419067808057e-05),
 np.float64(4.611138265271005e-05),
 np.float64(4.6681453371576876e-05),
 np.float64(4.4785418019166976e-05),
 np.float64(5.801911079025475e-05),
 np.float64(5.835543049144661e-05),
 np.float64(5.960225973969534e-05),
 np.float64(5.140051503529859e-05),
 np.float64(4.589163886207093e-05),
 np.float64(4.5347159816850297e-05),
 np.float64(5.1773181131665324e-05),
 np.float64(4.8129917689280956e-05),
 np.float64(4.674487272690411e-05),
 np.float64(5.076686257909284e-05),
 np.float64(5.245221802027969e-05),
 np.float64(5.153504106507587e-05),
 np.float64(5.4566678682126997e-05),
 np.float64(5.436667838159753e-05),
 np.float64(5.6371015903059895e-05),
 np.float64(5.6771317705959694e-05),
 np.float64(5.266458139555442e-05),
 np.float64(5.5280463863989374e-05),
 np.float64(4.6378809528469414e-05),
 np.float64(6.238603962074806e-05),
 np.float64(5.589208676185293e-05),
 np.float64(5.541141921837402e-05),
 np.float64(5.167287247999046e-05),
 np.float64(5.9618540327449515e-05),
 np.float64(4.652814539534336e-05),
 np.float64(4.8868532088546435e-05),
 np.float64(4.455712140545077e-05),
 np.float64(4.65372685375219e-05),
 np.float64(5.749230641361954e-05),
 np.float64(4.931626220171949e-05),
 np.float64(5.489796699392255e-05),
 np.float64(4.960015398783282e-05),
 np.float64(4.874880774587965e-05),
 np.float64(5.1489750922088814e-05),
 np.float64(4.933369376668398e-05),
 np.float64(4.9275791034595714e-05),
 np.float64(4.979050853784133e-05),
 np.float64(4.7653649115151115e-05),
 np.float64(4.781417597829105e-05),
 np.float64(5.010638619794446e-05),
 np.float64(5.488920885023094e-05),
 np.float64(5.1768009255533903e-05),
 np.float64(6.363149463149131e-05),
 np.float64(5.1183918691022325e-05),
 np.float64(4.932137801212734e-05),
 np.float64(5.002302133302265e-05),
 np.float64(5.787986120205682e-05),
 np.float64(5.9902844164876656e-05),
 np.float64(4.640009943808751e-05),
 np.float64(5.438598608144089e-05),
 np.float64(4.764950879613144e-05),
 np.float64(4.577237082160157e-05),
 np.float64(5.287947655839762e-05),
 np.float64(5.905946913445892e-05),
 np.float64(4.860730960297318e-05),
 np.float64(5.3985772544749654e-05),
 np.float64(5.097466055829103e-05),
 np.float64(4.6774255127475925e-05),
 np.float64(5.373171609744587e-05),
 np.float64(4.4792100687753864e-05),
 np.float64(4.385386308025617e-05),
 np.float64(7.287355683485773e-05),
 np.float64(4.737416404806206e-05),
 np.float64(4.9714886852956813e-05),
 np.float64(5.024372588736762e-05),
 np.float64(4.527460305767685e-05),
 np.float64(5.555959535745461e-05),
 np.float64(4.773156264146964e-05),
 np.float64(4.5690871735450655e-05),
 np.float64(4.65119727453059e-05),
 np.float64(5.048275021188813e-05),
 np.float64(6.407085477000863e-05),
 np.float64(4.577566717898951e-05),
 np.float64(5.235616716959201e-05),
 np.float64(4.659293738005345e-05),
 np.float64(4.941877815469038e-05),
 np.float64(5.003391237608873e-05),
 np.float64(5.212518435683805e-05),
 np.float64(4.7053860738815284e-05),
 np.float64(4.568052807634136e-05),
 np.float64(4.803563631565508e-05),
 np.float64(6.017718210645652e-05),
 np.float64(4.725379979565716e-05),
 np.float64(4.8654265775547056e-05),
 np.float64(5.000102568325541e-05),
 np.float64(5.285856037518532e-05),
 np.float64(4.9782341155602336e-05),
 np.float64(4.6782323987850146e-05),
 np.float64(7.959641037109452e-05),
 np.float64(4.776365914177539e-05),
 np.float64(4.729219583899274e-05),
 np.float64(5.00109091296249e-05),
 np.float64(4.7318902012298374e-05),
 np.float64(7.356160711560458e-05),
 np.float64(5.8851756451002914e-05),
 np.float64(4.90349746088244e-05),
 np.float64(4.821361336224569e-05),
 np.float64(4.91599354638013e-05),
 np.float64(4.782265451957891e-05),
 np.float64(5.4153296995941256e-05),
 np.float64(5.57225795334247e-05),
 np.float64(5.2314191787924776e-05),
 np.float64(5.284504382891599e-05),
 np.float64(5.754492910125672e-05),
 np.float64(4.958114610300348e-05),
 np.float64(4.473745920953282e-05),
 np.float64(5.2455788869035333e-05),
 np.float64(4.7282801037380353e-05),
 np.float64(4.773865906518061e-05),
 np.float64(4.707240777132524e-05),
 np.float64(4.8676840594690594e-05),
 np.float64(4.3783712364394934e-05),
 np.float64(5.586342177673258e-05),
 np.float64(4.8169475300290695e-05),
 np.float64(5.0554889548128094e-05),
 np.float64(4.723282758230766e-05),
 np.float64(4.662741207206097e-05),
 np.float64(6.012737995230004e-05),
 np.float64(4.6938681376267654e-05),
 np.float64(5.3559502687453824e-05),
 np.float64(5.104403225287472e-05),
 np.float64(4.908496536514095e-05),
 np.float64(4.724193245494344e-05),
 np.float64(4.8212802966240494e-05),
 np.float64(4.7242774208190585e-05),
 np.float64(4.76322474351242e-05),
 np.float64(5.011032770784195e-05),
 np.float64(5.009222362477881e-05),
 np.float64(4.7234635154499446e-05),
 np.float64(4.907586045978725e-05),
 np.float64(5.0113649925434325e-05),
 np.float64(4.511248157077821e-05),
 np.float64(4.6250086656247654e-05),
 np.float64(5.255277271247665e-05),
 np.float64(4.457799015460805e-05),
 np.float64(5.730128341786873e-05),
 np.float64(5.250461473733256e-05),
 np.float64(4.6091001663674837e-05),
 np.float64(5.182912095181365e-05),
 np.float64(5.489187064627076e-05),
 np.float64(5.2852674748793895e-05),
 np.float64(4.794266895359215e-05),
 np.float64(5.279386878544319e-05),
 np.float64(5.45940032502774e-05),
 np.float64(4.8050714033228014e-05),
 np.float64(5.7355271253162356e-05),
 np.float64(5.340166497261504e-05),
 np.float64(4.625505036271538e-05),
 np.float64(4.80633348271044e-05),
 np.float64(4.51110058744673e-05),
 np.float64(4.7423635298915325e-05),
 np.float64(4.8252556409135534e-05),
 np.float64(4.454206593203248e-05),
 np.float64(4.8082961294478086e-05),
 np.float64(5.553658468996713e-05),
 np.float64(4.87142680126248e-05),
 np.float64(4.949543441176316e-05),
 np.float64(4.495520947037586e-05),
 np.float64(4.624498906641692e-05),
 np.float64(6.023722140637699e-05),
 np.float64(4.71776401627985e-05),
 np.float64(5.229558231726066e-05),
 np.float64(4.603293626497358e-05),
 np.float64(7.354997658001036e-05),
 np.float64(4.821761810645699e-05),
 np.float64(5.410627098254143e-05),
 np.float64(6.552073974869987e-05),
 np.float64(5.360363099903317e-05),
 np.float64(5.129545205436593e-05),
 np.float64(4.869657577568005e-05),
 np.float64(4.819869134057955e-05),
 np.float64(4.5875898026319645e-05),
 np.float64(5.2621277477128314e-05),
 np.float64(4.904252394709266e-05),
 np.float64(4.4926244799740215e-05),
 np.float64(4.685123036930296e-05),
 np.float64(4.541124728574247e-05),
 np.float64(4.953954694367706e-05),
 np.float64(4.727478484146097e-05),
 np.float64(4.9197359795860365e-05),
 np.float64(4.8076514938914925e-05),
 np.float64(5.066014880857642e-05),
 np.float64(4.5476666916985405e-05),
 np.float64(4.840631669210575e-05),
 np.float64(4.949156995569178e-05),
 np.float64(4.8540052412589554e-05),
 np.float64(4.9516220229594576e-05),
 np.float64(5.851288430629554e-05),
 np.float64(6.345016461746041e-05),
 np.float64(5.216464231193954e-05),
 np.float64(6.53178371560688e-05),
 np.float64(4.8197328313164964e-05),
 np.float64(5.220491441845618e-05),
 np.float64(4.529339953129502e-05),
 np.float64(6.12918427895893e-05),
 np.float64(5.5380667960207736e-05),
 np.float64(4.632109786423845e-05),
 np.float64(5.0054521654510684e-05),
 np.float64(5.032491923695781e-05),
 np.float64(5.113275887237364e-05),
 np.float64(5.821105577352145e-05),
 np.float64(5.191575412813465e-05),
 np.float64(4.520983646123026e-05),
 np.float64(4.8026511409953574e-05),
 np.float64(4.884953452750393e-05),
 np.float64(4.9057043342994675e-05),
 np.float64(5.338266793763334e-05),
 np.float64(4.5070432440731147e-05),
 np.float64(4.598768787188768e-05),
 np.float64(6.0667328693288184e-05),
 np.float64(4.7253316715045076e-05),
 np.float64(4.916088996448394e-05),
 np.float64(5.998347231998742e-05),
 np.float64(5.1915194517727284e-05),
 np.float64(5.7161474480513904e-05),
 np.float64(4.888645862394864e-05),
 np.float64(5.3417223780089186e-05),
 np.float64(4.8469311942965904e-05),
 np.float64(5.081121464570406e-05),
 np.float64(4.99229949245561e-05),
 np.float64(5.168627582920401e-05),
 np.float64(4.509181014554875e-05),
 np.float64(5.028432385303631e-05),
 np.float64(4.526724043027657e-05),
 np.float64(5.652434887704208e-05),
 np.float64(4.553896661014917e-05),
 np.float64(4.731428912369945e-05),
 np.float64(5.357811146791493e-05),
 np.float64(4.4726037864992166e-05),
 np.float64(4.7918856156705404e-05),
 np.float64(5.523859663848802e-05),
 np.float64(4.4660092068071594e-05),
 np.float64(5.3000934685795424e-05),
 np.float64(4.9558064090618794e-05),
 np.float64(5.628833224581935e-05),
 np.float64(5.095436704446259e-05),
 np.float64(5.419105722371345e-05),
 np.float64(4.826666594182302e-05),
 np.float64(4.6701147525132876e-05),
 np.float64(4.784769243700722e-05),
 np.float64(4.9592327050676785e-05),
 np.float64(5.560625554677082e-05),
 np.float64(5.187037815445288e-05),
 np.float64(5.551502901715016e-05),
 np.float64(6.077405697606097e-05),
 np.float64(4.690707103292234e-05),
 np.float64(4.646484430732196e-05),
 np.float64(4.9722371291169274e-05),
 np.float64(5.264894123556422e-05),
 np.float64(5.62194722044518e-05),
 np.float64(4.363485827498404e-05),
 np.float64(5.8136765144531075e-05),
 np.float64(4.7414444286502306e-05),
 np.float64(5.006510714752701e-05),
 np.float64(4.538069635650971e-05),
 np.float64(4.713170890776817e-05),
 np.float64(5.04421098588144e-05),
 np.float64(5.945521011515747e-05),
 np.float64(5.2534047976478796e-05),
 np.float64(4.874673108422307e-05),
 np.float64(5.076708993029729e-05),
 np.float64(5.62654839772466e-05),
 np.float64(4.6412619786666626e-05),
 np.float64(4.4282471200904054e-05),
 np.float64(4.858441939429113e-05),
 np.float64(4.7625106004659036e-05),
 np.float64(5.0021139591406096e-05),
 np.float64(4.9482473728076926e-05),
 np.float64(5.2442073487937e-05),
 np.float64(4.6534743435963065e-05),
 np.float64(4.560757651432723e-05),
 np.float64(5.392416634738055e-05),
 np.float64(6.791482323039408e-05),
 np.float64(4.917623828359402e-05),
 np.float64(4.5489853643692806e-05),
 np.float64(4.9330039904093014e-05),
 np.float64(5.115539637388753e-05),
 np.float64(4.81187825218472e-05),
 np.float64(4.8080606560220366e-05),
 np.float64(4.926778200552057e-05),
 np.float64(5.227729123400786e-05),
 np.float64(5.146506364265222e-05),
 np.float64(5.956404354230286e-05),
 np.float64(4.7137093788282465e-05),
 np.float64(4.6480421692587264e-05),
 np.float64(4.6975675359278074e-05),
 np.float64(4.667113084437814e-05),
 np.float64(4.9667388065000155e-05),
 np.float64(4.913951351577847e-05),
 np.float64(4.8231756229416584e-05),
 np.float64(5.481556071711392e-05),
 np.float64(5.6036118078540154e-05),
 np.float64(4.7089878020569495e-05),
 np.float64(4.556172545062122e-05),
 np.float64(4.880348600462355e-05),
 np.float64(4.594344624310429e-05),
 np.float64(5.411725206707239e-05),
 np.float64(4.9471171787742934e-05),
 np.float64(5.945534405682294e-05),
 np.float64(4.810264207883481e-05),
 np.float64(5.41956137988972e-05),
 np.float64(4.453345047687395e-05),
 np.float64(5.3834903969219025e-05),
 np.float64(6.225300114591592e-05),
 np.float64(4.6856252769423455e-05),
 np.float64(4.481368421536403e-05),
 np.float64(4.4390107864740286e-05),
 np.float64(4.9145705192604104e-05),
 np.float64(4.768220648522834e-05),
 np.float64(4.897593325799095e-05),
 np.float64(5.178030399512111e-05),
 np.float64(4.96420300539276e-05),
 np.float64(5.626383938306752e-05),
 np.float64(5.239753607711222e-05),
 np.float64(5.278796770546466e-05),
 np.float64(6.00864072884195e-05),
 np.float64(5.3206844343785e-05),
 np.float64(4.6438430082718854e-05),
 np.float64(5.544624093504926e-05),
 np.float64(5.249130094344202e-05),
 np.float64(4.582382488591537e-05),
 np.float64(4.515413586544508e-05),
 np.float64(5.7454377237418945e-05),
 np.float64(4.478566547546361e-05),
 np.float64(4.730447199949964e-05),
 np.float64(5.0245390653816876e-05),
 np.float64(4.31643260786134e-05),
 np.float64(5.189794383320791e-05),
 np.float64(6.822765119691832e-05),
 np.float64(5.0849919664305065e-05),
 np.float64(4.8532976446411603e-05),
 np.float64(6.009659532872503e-05),
 np.float64(6.056943918587714e-05),
 np.float64(4.649857569537384e-05),
 np.float64(4.4082731512379285e-05),
 np.float64(4.61796464149229e-05),
 np.float64(4.907965683940454e-05),
 np.float64(4.992713462137575e-05),
 np.float64(4.980524837193788e-05),
 np.float64(5.5645506687215304e-05),
 np.float64(6.496666783582303e-05),
 np.float64(5.5908567950926294e-05),
 np.float64(4.85866398206564e-05),
 np.float64(5.89587442368393e-05),
 np.float64(4.49351809808299e-05),
 np.float64(4.927638380055023e-05),
 np.float64(4.5199104503434896e-05),
 np.float64(4.926379890919059e-05),
 np.float64(5.9284138476257916e-05),
 np.float64(7.001312813653554e-05),
 np.float64(5.797864019780098e-05),
 np.float64(6.011524358199431e-05),
 np.float64(4.628125127870239e-05),
 np.float64(4.586155724205666e-05),
 np.float64(4.536325918820597e-05),
 np.float64(5.2827000287977054e-05),
 np.float64(5.2350436437490225e-05),
 np.float64(5.160132726548581e-05),
 np.float64(4.893152185210343e-05),
 np.float64(4.489526742189678e-05),
 np.float64(4.890104407932897e-05),
 np.float64(4.4782361273527335e-05),
 np.float64(5.198934442585857e-05),
 np.float64(5.571472812700001e-05),
 np.float64(4.806224315919895e-05),
 np.float64(4.5505000643549333e-05),
 np.float64(4.687159368826004e-05),
 np.float64(4.3867221448887905e-05),
 np.float64(5.2027714999403456e-05),
 np.float64(5.191598863001424e-05),
 np.float64(4.7602246484731926e-05),
 np.float64(5.27733721106531e-05),
 np.float64(4.5986283320948404e-05),
 np.float64(4.5348606017620174e-05),
 np.float64(4.3410960245129646e-05),
 np.float64(4.797223124833144e-05),
 np.float64(4.451921595465467e-05),
 np.float64(4.822207251626395e-05),
 np.float64(6.188091700712578e-05),
 np.float64(4.358143859373441e-05),
 np.float64(4.8309263319222175e-05),
 np.float64(4.8500079399594606e-05),
 np.float64(4.873530875638704e-05),
 np.float64(4.7931428247564674e-05),
 np.float64(4.966477008586965e-05),
 np.float64(4.796071937770287e-05),
 np.float64(4.586354054342788e-05),
 np.float64(4.853615798084206e-05),
 np.float64(4.947595246470503e-05),
 np.float64(4.546642907047245e-05),
 np.float64(4.521053743561275e-05),
 np.float64(4.841274622302414e-05),
 np.float64(4.6769470367707714e-05),
 np.float64(4.8089356318996166e-05),

In [11]:
# Obtener la mínima semivarianza
min_semivar = min(semivar)
min_semivar

np.float64(4.3022171008343976e-05)

In [12]:
# Obtener los pesos del portafolio con mínima semivarianza
w_min_semivar = w_aleatorio[np.argmin(semivar)]

dict(zip(returns.columns, w_min_semivar*100))

{'CLX': np.float64(11.78043383741072),
 'COST': np.float64(13.537089029719343),
 'KHC': np.float64(3.629697154565678),
 'KO': np.float64(33.78668653192883),
 'PG': np.float64(11.008998614021582),
 'WMT': np.float64(26.25709483235384)}

---

### <font color='navy'> 3.- Portafolio Eficiente en Máximo Omega
    
    
Portafolio que maximiza el ratio omega de un portafolio de inversión, el ratio Omega mide la relación entre el upside risk (potencial de ganancias) y el downside risk (potencial de pérdidas) de un activo financiero.

**Separar los rendimientos en dos, aquellos por debajo de cero y los que están por encima de cero.**

$$R_{below, i} = min(r_i, 0)$$

$$R_{beneath, i} = max(r_i, 0)$$

In [26]:
below_zero = returns[returns < 0].fillna(0)
above_zero = returns[returns > 0].fillna(0)

**Calcular downside y upside risk para cada activo.**

$$\sigma_{d, i} = \sigma(R_{below, i})$$

$$\sigma_{u, i} = \sigma(R_{beneath, i})$$

In [27]:
upside = above_zero.std()
downside = below_zero.std()

In [30]:
upside * 100

Ticker
CLX     1.000773
COST    0.932918
KHC     1.046380
KO      0.771651
PG      0.798164
WMT     0.951844
dtype: float64

In [31]:
downside * 100

Ticker
CLX     1.062705
COST    0.905878
KHC     1.060862
KO      0.812780
PG      0.817945
WMT     0.873361
dtype: float64

**Calcular Omega individual para cada activo.**

$$\Omega_i = \frac{\sigma_{u, i}}{\sigma_{d, i}}$$

In [34]:
omegas = upside/downside

**Calcular Omega del portafolio y maximizarla cambiando ponderaciones.**

$$max_w \hspace{0.5cm} \Omega_p = \sum_{i=1}^{n} \Omega_i * w_i$$
    
$$s.a. \hspace{0.5cm} \sum_{i=1}^n w_i = 1$$
 
$$\hspace{0.8cm} w_i > 0 $$

In [51]:
# Simular portafolios con montecarlo
np.random.seed(30)
n_size = 1_000_000

w_aleatorio = np.random.dirichlet(np.ones(len(returns.columns)), size = n_size)

omegas_aleatorio = [np.dot(w, omegas) for w in w_aleatorio]

In [ ]:
# Obtener el maximo omega
np.argmax(omegas_aleatorio)

np.int64(558033)

In [54]:
# Obtener los pesos del portafolio con maximo omega
result = w_aleatorio[np.argmax(omegas_aleatorio)]
np.round(result, 6)

array([0.020678, 0.000997, 0.032488, 0.000143, 0.014705, 0.930989])

---

### 4.- Target Minimum Semivariance Portfolio
    

Ahora, supón que deseas optimizar las ponderaciones del portafolio considerando aquellos activos que tienen mayor probabilidad de superar a tu *benchmark*. Para ello, emplearás una estrategia basada en la *target semivariance*.

En este caso, asume que tu *benchmark* es el ETF `KXI`, que sigue el sector de bienes de consumo global. 
    
El objetivo es encontrar las ponderaciones óptimas que minimicen el riesgo de no superar el rendimiento de `KXI`. 
    
    
Recuerda que este enfoque ajustado al *benchmark* permite identificar aquellos activos que tienen un mejor desempeño relativo y, por lo tanto, una mayor probabilidad de generar *alpha*. Al minimizar la semivarianza relativa al *benchmark*, estarás optimizando el portafolio para que minimice el riesgo de rendimientos inferiores al de `KXI`.

Recuerda que los pasos son reiterativos y siguen la misma estructura que el método de mínima semivarianza, solo que ahora restarás los rendimientos al rendimiento del *benchmark* a los de tus activos.

In [56]:
# Descarga de Precios del Benchmark
benchmark = yf.download("KXI", start='2020-01-01', end='2026-03-06')["Close"]
benchmark.head(5)

/home/rigodev/ITESO/06/portafolios/env/lib/python3.12/site-packages/yfinance/scrapers/history.py:201: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
[*********************100%***********************]  1 of 1 completed

Ticker            KXI
Date
2020-01-02  47.864311
2020-01-03  47.821049
2020-01-06  47.968128
2020-01-07  47.656651
2020-01-08  47.647999

In [58]:
# Obtener rendimientos del benchmark
rets_benchmark = benchmark.pct_change().dropna()
rets_benchmark.head(5)

Ticker           KXI
Date
2020-01-03 -0.000904
2020-01-06  0.003076
2020-01-07 -0.006493
2020-01-08 -0.000182
2020-01-09  0.004721

In [59]:
# Sustraer rendimiento del benchmark de rendimientos individuales
diffs = returns - rets_benchmark.values
diffs

Ticker           CLX      COST       KHC        KO        PG       WMT
Date
2020-01-03  0.002870  0.001728 -0.010801 -0.004552 -0.005822 -0.007924
2020-01-06 -0.000067 -0.002801 -0.000835 -0.003441 -0.001689 -0.005111
2020-01-07 -0.005569  0.004917 -0.011073 -0.001189  0.000302 -0.002771
2020-01-08  0.003151  0.011646 -0.005345  0.002025  0.004444 -0.003250
2020-01-09  0.000741  0.011329 -0.005048  0.013494  0.006217  0.005609
...              ...       ...       ...       ...       ...       ...
2026-02-27 -0.009423  0.012822 -0.009923  0.001617  0.009518  0.016821
2026-03-02  0.015056  0.009874  0.013745  0.001379 -0.004261  0.011165
2026-03-03 -0.028855  0.020765  0.003947  0.004809 -0.007400  0.022152
2026-03-04 -0.028737  0.000947 -0.005463 -0.013660 -0.006922  0.001187
2026-03-05 -0.007105  0.000650  0.032562  0.010958 -0.002568 -0.010550

[1550 rows x 6 columns]

In [61]:
# Separar los rendimientos por debajo de cero
bz = diffs[diffs < 0].fillna(0)

In [ ]:
# Calcular target downside risk
target_downside = np.array(bz.std())

Ticker       CLX      COST       KHC        KO        PG       WMT
Ticker
CLX     0.000089  0.000022  0.000029  0.000016  0.000025  0.000022
COST    0.000022  0.000051  0.000018  0.000015  0.000018  0.000033
KHC     0.000029  0.000018  0.000066  0.000022  0.000022  0.000019
KO      0.000016  0.000015  0.000022  0.000024  0.000016  0.000014
PG      0.000025  0.000018  0.000022  0.000016  0.000026  0.000018
WMT     0.000022  0.000033  0.000019  0.000014  0.000018  0.000055

In [ ]:
# Calcular la matriz de target semivariance
target_semivar_matriz = target_downside.reshape(len(returns.columns), 1) @ target_downside.reshape(1, len(returns.columns)) * returns.corr()
target_semivar_matriz

In [ ]:
# Simular portafolios con montecarlo
targets = [w.T @ target_semivar_matriz @ w for w in w_aleatorio]

array([0.014436, 0.059756, 0.004049, 0.494697, 0.339955, 0.087107])

In [ ]:
# Obtener la mínima target semivariance
w_semivar_target = w_aleatorio[np.argmin(targets)]
w_semivar_target

{'CLX': np.float64(0.0144),
 'COST': np.float64(0.0598),
 'KHC': np.float64(0.004),
 'KO': np.float64(0.4947),
 'PG': np.float64(0.34),
 'WMT': np.float64(0.0871)}

In [83]:
# Obtener los pesos del portafolio con mínima semivarianza target
dict(zip(returns.columns, np.round(w_semivar_target, 4)*100))

{'CLX': np.float64(13.04),
 'COST': np.float64(14.21),
 'KHC': np.float64(4.49),
 'KO': np.float64(33.12),
 'PG': np.float64(10.31),
 'WMT': np.float64(24.84)}

In [74]:
dict(zip(returns.columns, w_min_semivar*100))

{'CLX': np.float64(11.78043383741072),
 'COST': np.float64(13.537089029719343),
 'KHC': np.float64(3.629697154565678),
 'KO': np.float64(33.78668653192883),
 'PG': np.float64(11.008998614021582),
 'WMT': np.float64(26.25709483235384)}

    ¡Excelente! Ahora comparemos las ponderaciones obtenidas en el método de semivarianza normal con target semivariance, responde: ¿Hay diferencias? ¿Como las interpretas?

---

### <font color='navy'> 5.- Reflexión

> **El método de la semivarianza y el ratio omega** son dos alternativas interesantes para la optimización de portafolios de inversión, ya que **replantean el concepto tradicional del riesgo financiero**.

> **¿Cuál es mejor?** No hay una respuesta definitiva; **la elección** del método "adecuado" **depende de varios factores**, como el perfil del inversionista, el comportamiento histórico de los activos seleccionados (que puede hacer que un método funcione mejor que otro) y las restricciones u objetivos específicos del gestor.

> Es importante resaltar nuevamente que estos **métodos solo son tan efectivos como lo sean los activos incluidos en el portafolio**.

> Hasta ahora, no hemos comparado las distintas estrategias de asignación de activos, sino que hemos enfocado en cómo determinar los pesos óptimos. **En las próximas sesiones, nos centraremos en la comparación y selección de estrategias de inversión**. Esto te permitirá, con un conjunto de activos que conforman un portafolio, evaluar sus características y elegir la mejor estrategia basándote en las métricas de los múltiples portafolios óptimos.

---

### <font color='navy'> Tarea 5

En equipos de dos integrantes, respondan los siguientes puntos y entreguen un archivo `html` con sus resultados. No olviden incluir los nombres de los integrantes en el archivo:

**Punto a)** Implementen tres funciones que optimicen portafolios utilizando: mínima semivarianza, ratio omega y semivarianza objetivo, empleando la función `scipy.optimize.minimize`.

**Punto b)** Construyan un portafolio compuesto por 5 activos financieros y optimícenlo con los tres métodos. Utilicen las funciones desarrolladas en el punto a) para realizar la optimización. Recuerden que, para el portafolio con semivarianza objetivo, deberán seleccionar un benchmark adecuado y consistente con los activos elegidos. Como respuesta a este punto, se esperan las ponderaciones eficientes y el valor óptimo de la función objetivo para cada método de Asset Allocation.

**Punto c)** Escriban una breve conclusión sobre las ventajas y desventajas que observan entre los métodos TMP y TPMP.

**Extra:** El equipo que logre la menor semivarianza global en su portafolio optimizado por mínima semivarianza recibirá 10 puntos extra para el segundo examen parcial. La selección de activos con una buena relación entre upside y downside será clave para obtener estos puntos.

In [75]:
diffs = returns - 0.05/252
diffs

Ticker           CLX      COST       KHC        KO        PG       WMT
Date
2020-01-03  0.001767  0.000625 -0.011903 -0.005654 -0.006924 -0.009026
2020-01-06  0.002810  0.000076  0.002042 -0.000564  0.001188 -0.002234
2020-01-07 -0.012261 -0.001775 -0.017765 -0.007881 -0.006390 -0.009463
2020-01-08  0.002772  0.011266 -0.005725  0.001645  0.004064 -0.003630
2020-01-09  0.005263  0.015852 -0.000525  0.018017  0.010739  0.010132
...              ...       ...       ...       ...       ...       ...
2026-02-27  0.001929  0.024175  0.001430  0.012969  0.020870  0.028173
2026-03-02 -0.002951 -0.008133 -0.004262 -0.016628 -0.022268 -0.006842
2026-03-03 -0.044832  0.004788 -0.012030 -0.011168 -0.023377  0.006175
2026-03-04 -0.030904 -0.001221 -0.007630 -0.015827 -0.009089 -0.000980
2026-03-05 -0.031962 -0.024207  0.007705 -0.013899 -0.027425 -0.035407

[1550 rows x 6 columns]

In [76]:
bz = diffs[diffs < 0].fillna(0)

In [77]:
# Calcular target downside risk
target_downside = np.array(bz.std())

In [78]:
# Calcular la matriz de target semivariance
target_semivar_matriz = target_downside.reshape(len(returns.columns), 1) @ target_downside.reshape(1, len(returns.columns)) * returns.corr()
target_semivar_matriz

Ticker       CLX      COST       KHC        KO        PG       WMT
Ticker
CLX     0.000114  0.000032  0.000043  0.000029  0.000045  0.000029
COST    0.000032  0.000083  0.000030  0.000032  0.000036  0.000049
KHC     0.000043  0.000030  0.000114  0.000048  0.000047  0.000030
KO      0.000029  0.000032  0.000048  0.000067  0.000044  0.000027
PG      0.000045  0.000036  0.000047  0.000044  0.000068  0.000035
WMT     0.000029  0.000049  0.000030  0.000027  0.000035  0.000077

In [79]:
# Simular portafolios con montecarlo
targets = [w.T @ target_semivar_matriz @ w for w in w_aleatorio]

In [80]:
# Obtener la mínima target semivariance
w_semivar_target = w_aleatorio[np.argmin(targets)]
w_semivar_target

array([0.130364, 0.14206 , 0.044891, 0.331208, 0.103067, 0.24841 ])

In [82]:
dict(zip(returns.columns, np.round(w_semivar_target, 4)*100))

{'CLX': np.float64(13.04),
 'COST': np.float64(14.21),
 'KHC': np.float64(4.49),
 'KO': np.float64(33.12),
 'PG': np.float64(10.31),
 'WMT': np.float64(24.84)}