<img style="float: left; margin: 30px 15px 15px 15px;" src="https://oci02.img.iteso.mx/Identidades-De-Instancia/ITESO/Logos%20ITESO/Logo-ITESO-Principal.jpg" width="400" height="600" /> 
    
    
## Portafolios de Inversión

### Growth Investing

Profesor: Sean Nicolás González Vázquez

###  Análisis Fundamental 
    
Tipo de análisis financiero que, como su nombre indica, se basa en los *fundamentales* de una empresa, es decir, en la información presentada en los tres principales estados financieros (Estado de Resultados, Flujo de Efectivo y Balance General) y en ratios calculados sobre la información presentada en estos tres estados financieros.  
    
El objetivo principal del análisis fundamental es determinar la salud financiera de una empresa, con el objetivo de ver si es conveniente invertir o no en esta, lo cual se decide en función de la metodología de inversión del gestor de inversiones.
    
El análisis fundamental es una herramienta que se utiliza para fundamentar la selección de un activo. La selección de activos es el primer paso del proceso de inversión en un portafolio.

### Value Investing
    

El **Value Investing**, es una fílosofia de inversión que busca invertir en negocios que tengan un valor de mercado menor a su valor intrínseco con la expectativa de que el mercado las revalúe correctamente. En término simples, esto significa comprar barato y vender caro. 
    

El Value Investing busca que el **valor extrínseco de una emisora** sea menor al **valor intrínseco dado a la emisora**, para buscar posibles **inflavaloraciones** o **sobrevaloraciones** de mercado:
    
+ *Acciones infravaloradas*: compañías que cotizan por debajo de su valor intrínseco, es decir, están baratas y sería conveniente comprar.  
    

+ *Acciones sobrevaloradas*: compañías que cotizan por encima de su valor intrínseco. Están caras y no sería buena opción de compra.
    
    
El concepto se mejoró posteriormente introduciendo el **long term value investing**, donde se buscan acciones que coticen a descuento, o cerca al *fair price* (Book Value = Market Value) y además, tengan una "*ventaja competitiva con durabilidad*".
    
 
### Growth Investing
    
    
El método inversión en *crecimiento* es una **estrategia que se centra en comprar acciones de empresas en fase de expansión cuyo valor se espera que crezca a tasas superiores al promedio del mercado**. En otras palabras, se buscan empresas con un potencial significativo de expansión en ingresos y ganancias en el futuro, además de una ventaja competitiva. Esta estrategia se basa en la creencia de que el crecimiento sostenido de una empresa impulsará el aumento del precio de sus acciones a largo plazo.

Algunas características clave del Growth Investing:

+ **Enfocado en el Crecimiento Empresarial**: Los inversores buscan empresas con sólidos fundamentos y un historial de crecimiento en ventas, beneficios y market share. 
    
    
+ **Poca Importancia a los Dividendos**: A diferencia de la estrategia de inversión en valor, donde los inversores buscan acciones subvaluadas con dividendos estables, la fílosofia de growth investing no prioriza los dividendos y se buscan empresas que reinvierten sus beneficios para financiar el crecimiento.  
    
    
+ **Alto Potencial de Rentabilidad a Largo Plazo**: La premisa básica del Growth Investing es que las empresas con un fuerte crecimiento tienen el potencial de generar rendimientos significativos a largo plazo, independientemente del valor actual. Estos inversores buscan capturar la apreciación del valor de las acciones a medida que la empresa crece.
    
    
+ **Volatilidad y Riesgo**: Dado que las empresas de crecimiento a menudo operan en industrias dinámicas y emergentes, las acciones de estas empresas pueden experimentar una mayor volatilidad en comparación con las empresas más establecidas. Existe un riesgo asociado con la incertidumbre sobre la capacidad de mantener altas tasas de crecimiento.
    
    
+ **Evaluación de Métricas de Crecimiento**: Los inversores de crecimiento analizan métricas clave como las tasas de crecimiento de ingresos, ganancias y márgenes para evaluar el potencial de crecimiento de una empresa. 
     

    
Ejemplos de empresas que podrían atraer a inversores de crecimiento incluyen aquellas en sectores tecnológicos, inteligencia artificial, biotecnología y otras industrias en rápido desarrollo.

Es importante destacar que el Growth Investing implica un enfoque a largo plazo y requiere paciencia, ya que el crecimiento de las empresas puede llevar tiempo en materializarse. Además, la selección cuidadosa de empresas con fundamentos sólidos es esencial para mitigar riesgos en esta estrategia.
    
+ **Importante**: Al invertir en empresas con una alta expectativa de crecimiento en el futuro, los inversionistas esperan también un retorno alto, por tanto, hay que estar conscientes que la volatilidad será mucho mayor que invertir en empresas consolidadas.
    
    
### Diferencias Growth y Value

    
| **Características**        | **Value Investing**                                                                 | **Growth Investing**                                                       |
|:---------------------------:|:--------------------------------------------------------------------------------------:|:----------------------------------------------------------------------------------:|
| **Enfoque Principal**       | Busca acciones subvaloradas o en descuento.                                           | Busca acciones de empresas con alto potencial de crecimiento.                     |
| **Criterio de Selección**   | Selecciona acciones que tienen un valor intrínseco superior al precio de mercado.      | Selecciona acciones de empresas con historial de fuerte crecimiento y potencial futuro. |
| **Tipo de Empresas Preferidas** | Tiende a favorecer empresas establecidas, con sólidos fundamentos y dividendos.       | Prefiere empresas con potencial de expansión futura.                              |
| **Métricas Clave**          | P/E bajo, P/B bajo, dividendos sólidos.                                               | Crecimiento de ingresos, ganancias, ROE, márgenes de beneficio.                  |
| **Enfoque en Dividendos**   | Sí, muchas acciones de valor pagan dividendos.                                        | No necesariamente; muchas empresas de crecimiento reinvierten ganancias en lugar de pagar dividendos. |
| **Horizonte de Inversión**  | A mediano plazo; busca beneficios a medida que el mercado reconoce el verdadero valor de las acciones. | A largo plazo; espera que el crecimiento de las empresas impulse el rendimiento.  |
| **Riesgos Considerados**    | Riesgo de valoración incorrecta; las acciones pueden permanecer subvaloradas durante períodos prolongados. | Riesgo de que las empresas de crecimiento no alcancen las expectativas de crecimiento; mayor volatilidad. |
| **Ejemplos de Inversores Famosos** | Warren Buffett, Benjamin Graham.                                                  | Peter Lynch.                                                                      |

    
La metodología que utiliza una visión "*en medio*" de ambas estrategias se denomina GARP (*Growth at Reasonable Price*).
    
### Factores clave para seleccionar empresas usando Growth Investing 
    
    
1.- Crecimiento Histórico de las Ganancias.
       
    
2.- Márgenes de Beneficio Sólidos
    
    
3.- Fuerte Retorno sobre el Patrimonio 
    

4.- Fuerte Rendimiento de Acciones
    

A continuación, ahondaremos en cada punto y como descargar esta información utilizando yahoo finance

## Práctica: Growth Investing  
    
    
### 0. Descarga de Fundamentales

In [1]:
# Importar librerías
import numpy as np
import pandas as pd
import yfinance as yf
import datetime

import matplotlib.pyplot as plt

In [2]:
# Bajar un precio en una fecha dada
def get_historical_price(ticker: str, start: str):
    end = start+datetime.timedelta(days=4)
    price=pd.DataFrame(yf.Ticker(ticker).history(start=start, end=end)["Close"])
    return price.iloc[0, 0]

In [3]:
ticker = 'MELI'

In [4]:
info = yf.Ticker(ticker=ticker)

In [5]:
# Funcion para obtener estados financieros
balance = info.balancesheet.iloc[:,:-1]
estado = info.income_stmt.iloc[:,:-1]
cash = info.cash_flow.iloc[:, :-1]

/home/rigodev/ITESO/06/portafolios/env/lib/python3.12/site-packages/yfinance/scrapers/fundamentals.py:120: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  end = pd.Timestamp.utcnow().ceil("D")

/home/rigodev/ITESO/06/portafolios/env/lib/python3.12/site-packages/yfinance/scrapers/fundamentals.py:120: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  end = pd.Timestamp.utcnow().ceil("D")
/home/rigodev/ITESO/06/portafolios/env/lib/python3.12/site-packages/yfinance/scrapers/fundamentals.py:120: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  end = pd.Timestamp.utcnow().ceil("D")

### 1.- Fuerte Crecimiento Histórico de Ganancias

Las empresas deben demostrar un historial de sólido crecimiento de ganancias en los últimos tres a diez años. El ratio financiero que nos puede ayudar a medir cuantitativamente esto es el EPS:
    
+ **EPS:** Múltiplio financiero que nos indica el beneficio por acción que tiene una compañía, en teoría, indica la cantidad de ingresos que le corresponde a cada inversionista por cada acción que tiene.
    
    
$$EPS = \frac{Income}{Shares}$$
    

    
    
El crecimiento mínimo de las ganancias por acción (EPS) en *Growth Investing* depende del tamaño de la empresa: por ejemplo, podrías buscar un crecimiento de al menos el 5% para empresas que superen los $4$ mil millones, el $7%$ para aquellas en el rango de $400$ millones a $4$ mil millones, y el $12%$ para empresas más pequeñas por debajo de los $400$ millones. La idea principal es que si la empresa ha mostrado un buen crecimiento en el pasado reciente, es probable que continúe haciéndolo en el futuro.

    
Además, las empresas objeto de inversión por medio de Growth Investing, muestran un price earnings ratio (*PER*) arriba de 25, lo que en Value Investing indicaría una sobre-valoración alta de un activo financiero.
    
    
+ **PER:** Indica cuántas veces se está pagando el beneficio neto anual de una empresa determinada al comprar una acción de esta, es decir, que tan cara o barata esta una acción, en función de su utilidad real y cuánto cuesta comprar una parte de la empresa.
    
$$PER = \frac{Price}{Income/Shares} = \frac{Price}{Earnings Per Share}$$

In [6]:
net_income = estado.loc["Net Income Common Stockholders"]
n_shares = balance.loc["Ordinary Shares Number"]

In [7]:
net_income / 1_000_000

2025-12-31    1997.0
2024-12-31    1911.0
2023-12-31     987.0
2022-12-31     482.0
Name: Net Income Common Stockholders, dtype: float64

In [8]:
n_shares / 1_000_000

2025-12-31    50.697182
2024-12-31    50.697375
2023-12-31    50.697442
2022-12-31    50.257751
Name: Ordinary Shares Number, dtype: float64

In [9]:
EPS = net_income / n_shares
EPS

2025-12-31    39.390750
2024-12-31    37.694259
2023-12-31    19.468438
2022-12-31     9.590560
dtype: float64

In [10]:
dates = list(balance.columns)

prices = [get_historical_price(ticker=ticker,start=date) for date in dates]
prices

/home/rigodev/ITESO/06/portafolios/env/lib/python3.12/site-packages/yfinance/scrapers/history.py:201: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
/home/rigodev/ITESO/06/portafolios/env/lib/python3.12/site-packages/yfinance/scrapers/history.py:201: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
/home/rigodev/ITESO/06/portafolios/env/lib/python3.12/site-packages/yfinance/scrapers/history.py:201: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
/home/rigodev/ITESO/06/portafolios/env/lib/python3.12/site-packages/yfinance/scrapers/history.py:201: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()

[np.float64(2014.260009765625),
 np.float64(1700.43994140625),
 np.float64(1529.1600341796875),
 np.float64(826.1099853515625)]

In [11]:
prices / EPS

2025-12-31    51.135356
2024-12-31    45.111377
2023-12-31    78.545595
2022-12-31    86.137821
dtype: float64

### 2.- Márgenes de Beneficio Sólidos
    
    
El **profit margin** o margen de beneficio antes de impuestos de una empresa se calcula restando todos los gastos de las ventas (excepto impuestos) y dividiendo por las ventas. Es una métrica importante a considerar porque una empresa puede tener un crecimiento fantástico en ventas con ganancias pobres, lo que podría indicar que la administración no está controlando costos y ingresos.
    
 $$PM = \frac{\text{Income before Tax}}{\text{Sales or Gross Revenue}}$$

    
El porcentaje de profit margin considerado "bueno" depende de la industria, ya que los márgenes varían significativamente según el sector. Sin embargo, como regla general:
    
- **Financials:** 10%-20%    
    
    
- **Healthcare:**  15%-20%    
    
    
- **Consumer Staples:** 5%-10%   
    
 
- **Consumer Discretionary:** 10%-20%    
    

- **Technology:** 15%-25%  
    

- **Energy:** 5%-15%    
    

- **Real Estate :** 30%-40%    
    

- **Industrials:** 5%-10%    
    

- **Utilities:** 10%-15%    
    

- **Telecommunications:** 10%-15%    
    

- **Transportation:** 5%-10%

In [12]:
pd.options.display.float_format = "{:.2f}".format

estado / estado.loc["Total Revenue"] * 100

,2025-12-31,2024-12-31,2023-12-31,2022-12-31
Tax Effect Of Unusual Items,-0.35,-0.19,-1.49,-0.70
Tax Rate For Calcs,0.00,0.00,0.00,0.00
Normalized EBITDA,14.39,16.34,18.97,14.06
Total Unusual Items,-1.17,-0.88,-4.07,-1.84
Total Unusual Items Excluding Goodwill,-1.17,-0.88,-4.07,-1.84
Net Income From Continuing Operation Net Minority Interest,6.91,9.20,6.53,4.47
Reconciled Depreciation,2.83,2.97,3.47,3.74
Reconciled Cost Of Revenue,55.50,53.91,49.76,51.78
EBITDA,13.22,15.47,14.90,12.23
EBIT,10.39,12.50,11.43,8.49
Net Interest Income,-0.08,-0.08,-0.26,-0.84
Interest Expense,0.55,0.79,1.15,1.25
Interest Income,0.48,0.71,0.89,0.41
Normalized Income,7.73,9.89,9.11,5.61
Net Income From Continuing And Discontinued Operation,6.91,9.20,6.53,4.47
Total Expenses,88.92,87.34,85.39,90.08
Total Operating Income As Reported,11.08,12.66,14.61,9.92
Diluted Average Shares,0.18,0.24,0.34,0.48
Basic Average Shares,0.18,0.24,0.14,0.47
Diluted EPS,0.00,0.00,0.00,0.00
Basic EPS,0.00,0.00,0.00,0.00
Diluted NI Availto Com Stockholders,6.91,9.20,6.53,4.54
Average Dilution Earnings,NaN,0.00,0.04,0.06
Net Income Common Stockholders,6.91,9.20,6.53,4.47
Otherunder Preferred Stock Dividend,NaN,0.00,0.00,0.00
Net Income,6.91,9.20,6.53,4.47
Net Income Including Noncontrolling Interests,6.91,9.20,6.53,4.47
Net Income Continuous Operations,6.91,9.20,6.53,4.47
Earnings From Equity Interest Net Of Tax,0.00,0.00,0.02,0.00
Tax Provision,2.92,2.51,3.77,2.76
Pretax Income,9.84,11.71,10.28,7.24
Other Income Expense,-1.17,-0.88,-4.07,-1.84
Gain On Sale Of Security,-1.17,-0.88,-4.07,-1.84
Net Non Operating Interest Income Expense,-0.08,-0.08,-0.26,-0.84
Interest Expense Non Operating,0.55,0.79,1.15,1.25
Interest Income Non Operating,0.48,0.71,0.89,0.41
Operating Income,11.08,12.66,14.61,9.92
Operating Expense,33.42,33.43,35.63,38.30
Provision For Doubtful Accounts,10.70,8.94,6.95,9.95
Research And Development,7.85,9.31,12.12,10.19
Selling General And Administration,14.87,15.18,16.56,18.15
Selling And Marketing Expense,11.14,10.55,11.49,12.02
General And Administrative Expense,3.73,4.63,5.07,6.13
Other Gand A,3.73,4.63,5.07,6.13
Gross Profit,44.50,46.09,50.24,48.22
Cost Of Revenue,55.50,53.91,49.76,51.78
Total Revenue,100.00,100.00,100.00,100.00
Operating Revenue,100.00,100.00,100.00,100.00

### 3.- Fuerte Retorno sobre el Patrimonio
    
El **ROE** de una empresa mide la rentabilidad al revelar cuánto beneficio genera con el dinero que los accionistas han invertido, en pocas palabras, que tanto provecho  le esta sacando una empresa al capital que  tiene:
    
$$ROE = \frac{Income}{Equity}$$
    
Se calcula dividiendo el ingreso neto entre el patrimonio de los accionistas. Una buena regla es comparar el ROE actual de una empresa con el ROE de tres-cinco años de la empresa y de la industria. Un ROE estable o en aumento indica que la administración está generando buenos rendimientos de las inversiones de los accionistas y opera eficientemente el negocio.
    
+ Si el resultado es inferior a 3, la situación es mala; si está entre 3 y 8, es normal; si es superior a 8, es buena. Se espera un resultado consistente y en crecimiento.

In [19]:
book_value = balance.loc["Ordinary Shares Number"]
book_value

2025-12-31   50697182.00
2024-12-31   50697375.00
2023-12-31   50697442.00
2022-12-31   50257751.00
Name: Ordinary Shares Number, dtype: float64

In [20]:
net_income / book_value

2025-12-31   39.39
2024-12-31   37.69
2023-12-31   19.47
2022-12-31    9.59
dtype: float64

### 4.- Fuerte Rendimiento de Acciones
    
    
Se buscan acciones que puedan que duplicar su crecimiento anual en cinco años, si no probablemente no sea una acción objeto de inversión en *growth investing*. Cabe destacar que al buscar un crecimiento tan fuerte, se debe de aceptar también una volatilidad mayor.
    
Ten en cuenta que el precio de una acción se duplicaría en siete años con una tasa de crecimiento del 11%. Para duplicarse en cinco años, la tasa de crecimiento debe ser de aproximadamente 15%, algo ciertamente factible para empresas en industrias de rápido crecimiento o con una ventaja competitiva.

In [21]:
prices = yf.download(tickers=ticker, start = '2020-01-01')["Close"]
prices.head(3)

/home/rigodev/ITESO/06/portafolios/env/lib/python3.12/site-packages/yfinance/scrapers/history.py:144: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  end_dt = pd.Timestamp.utcnow().tz_convert(tz)
/home/rigodev/ITESO/06/portafolios/env/lib/python3.12/site-packages/yfinance/scrapers/history.py:201: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
[*********************100%***********************]  1 of 1 completed

Ticker       MELI
Date
2020-01-02 610.19
2020-01-03 607.80
2020-01-06 606.55

In [25]:
returns = prices.pct_change().dropna()
mean = returns.mean() * 252 * 100

In [26]:
std = returns.std() * np.sqrt(252) * 100

In [28]:
mean
std

Ticker
MELI   51.27
dtype: float64