# Repaso

In [2]:
import pandas as pd
import numpy as np

In [45]:
df = pd.DataFrame(columns=["VOO", "TSLA", "AMZN", "IWM"])

capital_inicial = 1_000_000

df.loc["pes_objetivos"] = [0.25, 0.15, 0.40, 0.20]

df.loc["precio_t=0"] = [420.10, 255.20, 103.40, 188.55]

df.loc["no_stock"] = np.floor((capital_inicial * df.loc["pes_objetivos"]) / df.loc["precio_t=0"])

df.loc["allocation_t=0"] = df.loc["no_stock"] * df.loc["precio_t=0"]

df

                      VOO       TSLA      AMZN        IWM
pes_objetivos        0.25       0.15       0.4       0.20
precio_t=0         420.10     255.20     103.4     188.55
no_stock           595.00     587.00    3868.0    1060.00
allocation_t=0  249959.50  149802.40  399951.2  199863.00

In [49]:
df.loc["precio_t=6"] = [450.50, 210.30, 121.50, 203.40]

df.loc["allocation_t=6"] = df.loc["no_stock"] * df.loc["precio_t=6"]

df

                      VOO       TSLA      AMZN        IWM
pes_objetivos        0.25       0.15       0.4       0.20
precio_t=0         420.10     255.20     103.4     188.55
no_stock           595.00     587.00    3868.0    1060.00
allocation_t=0  249959.50  149802.40  399951.2  199863.00
precio_t=6         450.50     210.30     121.5     203.40
allocation_t=6  268047.50  123446.10  469962.0  215604.00

In [50]:
df.loc["pesos_t=6"] = df.loc["allocation_t=6"] / sum(df.loc["allocation_t=6"])

df

                         VOO           TSLA           AMZN            IWM
pes_objetivos        0.25000       0.150000       0.400000       0.200000
precio_t=0         420.10000     255.200000     103.400000     188.550000
no_stock           595.00000     587.000000    3868.000000    1060.000000
allocation_t=0  249959.50000  149802.400000  399951.200000  199863.000000
precio_t=6         450.50000     210.300000     121.500000     203.400000
allocation_t=6  268047.50000  123446.100000  469962.000000  215604.000000
pesos_t=6            0.24887       0.114614       0.436338       0.200178

In [51]:
df.loc[["pesos_t=6", "pes_objetivos"], :]

                   VOO      TSLA      AMZN       IWM
pesos_t=6      0.24887  0.114614  0.436338  0.200178
pes_objetivos  0.25000  0.150000  0.400000  0.200000

In [ ]:
df

                         VOO           TSLA          AMZN            IWM
pes_objetivos       0.250000       0.150000       0.40000       0.200000
precio_t=0        420.100000     225.200000     103.40000     188.550000
no_stock          595.000000     666.000000    3868.00000    1060.000000
precio_t=6        450.500000     210.300000     121.50000     203.400000
df_allocation  268047.500000  140059.800000  469962.00000  215604.000000
pesos_t=6           0.245089       0.128064       0.42971       0.197137

In [53]:
((df.loc["pesos_t=6"] - df.loc["pes_objetivos"]) * sum(df.loc["allocation_t=6"])) / df.loc["precio_t=6"]

VOO      -2.702331
TSLA   -181.230813
AMZN    322.124774
IWM       0.944346
dtype: float64

In [11]:
df.loc["precio_t=6"] = [115.21, 95.30, 605.20, 420.21]

df.loc["df_allocation"] = df.loc["no_stock"] * df.loc["precio_t=6"]
df

                      SHV         NKE         NOW         QQQ
pes_objetivos       0.105       0.192       0.316       0.387
precio_t=0        110.450     110.370     561.950     369.420
no_stock          950.000    1739.000     562.000    1047.000
precio_t=6        115.210      95.300     605.200     420.210
df_allocation  109449.500  165726.700  340122.400  439959.870

In [17]:
df.loc["pesos_t=6"] = df.loc["df_allocation"] / sum(df.loc["df_allocation"])
df.loc[["pesos_t=6", "pes_objetivos"], :]

                    SHV       NKE       NOW       QQQ
pesos_t=6      0.103718  0.157048  0.322312  0.416921
pes_objetivos  0.105000  0.192000  0.316000  0.387000

In [23]:
((df.loc["pesos_t=6"] - df.loc["pes_objetivos"]) * sum(df.loc["df_allocation"])) / df.loc["precio_t=6"]

SHV    -11.740642
NKE   -387.019163
NOW     11.005822
QQQ     75.140625
dtype: float64

In [24]:
ADV = 230_087

no_shares = 507_762

no_shares / ADV

2.2068261136005076

In [3]:

df = pd.DataFrame(columns=["VOO", "TSLA", "AMZN", "IWM"])

capital_inicial = 1_000_000

df.loc["pes_objetivos"] = [0.25, 0.15, 0.40, 0.20]

df.loc["precio_t=0"] = [420.10, 255.20, 103.40, 188.55]

df.loc["no_stock"] = np.floor((capital_inicial * df.loc["pes_objetivos"]) / df.loc["precio_t=0"])

df.loc["allocation_t=0"] = df.loc["no_stock"] * df.loc["precio_t=0"]

df.loc["precio_t=6"] = [450.50, 210.30, 121.50, 203.40]

df.loc["allocation_t=6"] = df.loc["no_stock"] * df.loc["precio_t=6"]

df.loc["pesos_t=6"] = df.loc["allocation_t=6"] / sum(df.loc["allocation_t=6"])

((df.loc["pesos_t=6"] - df.loc["pes_objetivos"]) * sum(df.loc["allocation_t=6"])) / df.loc["precio_t=6"]

VOO      -2.702331
TSLA   -181.230813
AMZN    322.124774
IWM       0.944346
dtype: float64