In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.options.display.float_format = "{:,.6f}".format

In [ ]:
precios = pd.DataFrame([100, 100.4, 100.099, 100.3993], columns=["precio"])

benchmark = pd.DataFrame([100, 100.2, 100.0998, 100.3], columns=["precio"])

precios

      precio
0 100.000000
1 100.400000
2 100.099000
3 100.399300

In [7]:
rendimiento_t1 = precios.iloc[1] / precios.iloc[0] -1
rendimiento_t1

precio   0.004000
dtype: float64

In [ ]:
returns = precios.pct_change().dropna()
returns.mean()

precio   0.133401
dtype: float64

In [14]:
returns_benchmark = benchmark.pct_change().dropna()
returns_benchmark.mean() * 252 * 100

precio   25.200034
dtype: float64

#### 4

In [34]:
precios_b = pd.DataFrame([100, 99.9, 100.1997, 100.4001], columns=["precios_b"])

In [35]:
returns_b = precios_b.pct_change().dropna()

mean_return_b = returns_b.mean()

In [36]:
mean_return_a = returns.mean()

In [ ]:
#rendimiento de un portafolio 50%-50%
w = np.array([0.5, 0.5])
portfolio_return = pd.concat([returns, returns_b], axis = 1)
portfolio_return

     precio  precios_b
1  0.004000  -0.001000
2 -0.002998   0.003000
3  0.003000   0.002000

In [ ]:
PI = np.sum(w  * portfolio_return, axis=1)
PI * 100

1   0.150000
2   0.000100
3   0.250002
dtype: float64

In [44]:
w @ np.array([mean_return_a, mean_return_b]) * 252 * 100

array([33.60851756])

In [45]:
portfolio_return.cov()

             precio  precios_b
precio     0.000014  -0.000006
precios_b -0.000006   0.000004

#### 9

In [47]:
cov = np.array([
    [0.04, 0.01], [0.01, 0.09   ]
])

w = np.array([0.25, 0.75])

result = w.T @ cov @ w
result

np.float64(0.056874999999999995)

In [51]:
cov = np.array([
    [0.0009, 0.0003], 
    [0.0003, 0.0004]
])

w = np.array([0.6, 0.4])

w.T @ cov @ w

np.float64(0.000532)

## Segundo cuestionario

In [52]:
A = pd.DataFrame([100.0000,101.0000,99.9900,101.4899,101.0839,102.0947], columns=["precio A"])
B = pd.DataFrame([100.0000, 99.5000, 100.6940, 100.1905, 100.9921, 101.3960], columns=["precio B"])
M = pd.DataFrame([100.0000, 100.3000, 100.0994, 100.7000, 100.4986, 101.1016], columns=["benchmark"])

w = np.array([0.7, 0.3])

In [53]:
return_t2 = A.iloc[2] / A.iloc[1] - 1
return_t2

precio A   -0.010000
dtype: float64

In [54]:
returns_a = A.pct_change().dropna()
returns_b = B.pct_change().dropna()
returns_benchmark = M.pct_change().dropna()

In [56]:
returns_b.mean() * 100

precio B   0.279996
dtype: float64

In [57]:
returns_benchmark.mean() * 252 * 100

benchmark   55.440603
dtype: float64

In [ ]:
P =np.sum(w * pd.concat([A, B], axis = 1), axis = 1)
P

0   100.000000
1   100.550000
2   100.201200
3   101.100080
4   101.056360
5   101.885090
dtype: float64

In [61]:
returns_p = P.pct_change().dropna()
returns_p * 100

1    0.550000
2   -0.346892
3    0.897075
4   -0.043244
5    0.820067
dtype: float64

In [62]:
returns_p.mean() * 252 * 100

np.float64(94.60109493441618)

In [64]:
prices = pd.concat([A, B, M], axis = 1)
returns = prices.pct_change().dropna()

returns.corr()

           precio A  precio B  benchmark
precio A   1.000000 -0.907212   0.944575
precio B  -0.907212  1.000000  -0.744263
benchmark  0.944575 -0.744263   1.000000

In [70]:
betas = returns.cov()["benchmark"] / returns.cov()["benchmark"]["benchmark"]
betas

precio A     2.496925
precio B    -1.416756
benchmark    1.000000
Name: benchmark, dtype: float64

In [71]:
rf = 0.04
Erm = 0.1

CAPM_A = rf + betas["precio A"] * (Erm - rf)
CAPM_A

np.float64(0.18981547272137572)

In [ ]:
returns_a.mean()

precio A   1.058386
dtype: float64

In [78]:
P_cov = returns.iloc[:, :2].cov() 

w.T @ P_cov @ w * 100

np.float64(0.002969174124398984)

In [79]:
# Downside risk A

downside_risk_a = returns_a[returns_a < 0].fillna(0)
downside_risk_a

   precio A
1  0.000000
2 -0.010000
3  0.000000
4 -0.004000
5  0.000000

In [83]:
filter_target = returns_a - returns_benchmark.values
filter_target

   precio A
1  0.007000
2 -0.008000
3  0.009000
4 -0.002000
5  0.004000

In [84]:
# Target Downside Risk
target_downside_risk_a = filter_target[filter_target < 0].fillna(0)
target_downside_risk_a

   precio A
1  0.000000
2 -0.008000
3  0.000000
4 -0.002000
5  0.000000

In [85]:
S = np.array([
    [0.0000192, -0.00001089],
    [-0.00001089, 0.0000075]
])

w.T @ S @ w

np.float64(5.509199999999999e-06)

In [86]:
V0 = 1_000

evol = V0 * (1 + returns_p).cumprod()
evol

1   1,005.500000
2   1,002.012000
3   1,011.000800
4   1,010.563600
5   1,018.850900
dtype: float64